karyawan/urls.py
from django.urls import path
from . import views

app_name='karyawan'

urlpatterns = [
    #cari berkas karyawan ajax
    path('cari-berkas/<int:karyawan_id>', views.berkas_list, name = 'berkas_list'),
    
    #cv saya
    path('edit-data-karyawan-saya', views.datakaryawansaya, name = 'data-karyawan-saya'),
    
    #cv saya
    path('curriculum-vitae', views.cv_saya, name = 'cv_saya'),
    path('curriculum-vitae/<int:id>', views.cv_karyawan, name = 'cv_karyawan'),
    path('curriculum-vitae/cetak-id-card/<int:id>', views.printidcardkaryawan, name = 'print-idcard-karyawan'),
    
    # karyawan
	path('index',views.index,name='index'),
	path('create',views.create,name='create'),
	path('edit/<int:id>',views.edit,name='edit'),
	path('show/<int:id>',views.show,name='show'),
	path('destroy/<int:id>',views.destroy,name='destroy'),
    
	# berkas saya
	path('absensi-karyawan',views.indexabsensikaryawan,name='absensi-karyawan'),
	path('absensi-karyawan/<int:id>',views.showabsensikaryawan,name='absensi-karyawan-show'),
    
	# berkas saya
	path('berkas-saya',views.indexberkassaya,name='berkas-saya-index'),
    path('create-berkas-saya',views.createberkassaya,name='berkas-saya-create'),
	path('show-berkas-saya/<int:id>',views.showberkassaya,name='berkas-saya-show'),
	path('edit-berkas-saya/<int:id>',views.editberkassaya,name='berkas-saya-edit'),
	path('destroy-berkas-saya/<int:id>',views.destroyberkassaya,name='berkas-saya-destroy'),
    
	# berkas karyawan
	path('berkas-karyawan',views.indexberkaskaryawan,name='berkas-karyawan-index'),
	path('create-berkas-karyawan',views.createberkaskaryawan,name='berkas-karyawan-create'),
	path('show-berkas-karyawan/<int:id>',views.showberkaskaryawan,name='berkas-karyawan-show'),
	path('edit-berkas-karyawan/<int:id>',views.editberkaskaryawan,name='berkas-karyawan-edit'),
	path('destroy-berkas-karyawan/<int:id>',views.destroyberkaskaryawan,name='berkas-karyawan-destroy'),
	
	# Karir karyawan
	path('karir-karyawan',views.indexkarirkaryawan,name='karir-karyawan-index'),
	path('create-karir-karyawan',views.createkarirkaryawan,name='karir-karyawan-create'),
	path('show-karir-karyawan/<int:id>',views.showkarirkaryawan,name='karir-karyawan-show'),
	path('edit-karir-karyawan/<int:id>',views.editkarirkaryawan,name='karir-karyawan-edit'),
	path('destroy-karir-karyawan/<int:id>',views.destroykarirkaryawan,name='karir-karyawan-destroy'),
    
	# karir saya
	path('karir-saya',views.indexkarirsaya,name='karir-saya-index'),
    path('create-karir-saya',views.createkarirsaya,name='karir-saya-create'),
	path('show-karir-saya/<int:id>',views.showkarirsaya,name='karir-saya-show'),
	path('edit-karir-saya/<int:id>',views.editkarirsaya,name='karir-saya-edit'),
	path('destroy-karir-saya/<int:id>',views.destroykarirsaya,name='karir-saya-destroy'),
    
	# Riwayat Pendidikan karyawan
	path('riwayat-pendidikan-karyawan',views.indexriwayatpendidikankaryawan,name='riwayat-pendidikan-karyawan-index'),
	path('create-riwayat-pendidikan-karyawan',views.createriwayatpendidikankaryawan,name='riwayat-pendidikan-karyawan-create'),
	path('show-riwayat-pendidikan-karyawan/<int:id>',views.showriwayatpendidikankaryawan,name='riwayat-pendidikan-karyawan-show'),
	path('edit-riwayat-pendidikan-karyawan/<int:id>',views.editriwayatpendidikankaryawan,name='riwayat-pendidikan-karyawan-edit'),
	path('destroy-riwayat-pendidikan-karyawan/<int:id>',views.destroyriwayatpendidikankaryawan,name='riwayat-pendidikan-karyawan-destroy'),
    
	# Riwayat Pendidikan saya
	path('riwayat-pendidikan-saya',views.indexriwayatpendidikansaya,name='riwayat-pendidikan-saya-index'),
    path('create-riwayat-pendidikan-saya',views.createriwayatpendidikansaya,name='riwayat-pendidikan-saya-create'),
	path('show-riwayat-pendidikan-saya/<int:id>',views.showriwayatpendidikansaya,name='riwayat-pendidikan-saya-show'),
	path('edit-riwayat-pendidikan-saya/<int:id>',views.editriwayatpendidikansaya,name='riwayat-pendidikan-saya-edit'),
	path('destroy-riwayat-pendidikan-saya/<int:id>',views.destroyriwayatpendidikansaya,name='riwayat-pendidikan-saya-destroy'),
	
	# Pelatihan karyawan
	path('pelatihan-karyawan',views.indexpelatihankaryawan,name='pelatihan-karyawan-index'),
	path('create-pelatihan-karyawan',views.createpelatihankaryawan,name='pelatihan-karyawan-create'),
	path('show-pelatihan-karyawan/<int:id>',views.showpelatihankaryawan,name='pelatihan-karyawan-show'),
	path('edit-pelatihan-karyawan/<int:id>',views.editpelatihankaryawan,name='pelatihan-karyawan-edit'),
	path('destroy-pelatihan-karyawan/<int:id>',views.destroypelatihankaryawan,name='pelatihan-karyawan-destroy'),
    
	# Pelatihan Saya
	path('pelatihan-saya',views.indexpelatihansaya,name='pelatihan-saya-index'),
	path('create-pelatihan-saya',views.createpelatihansaya,name='pelatihan-saya-create'),
	path('show-pelatihan-saya/<int:id>',views.showpelatihansaya,name='pelatihan-saya-show'),
	path('edit-pelatihan-saya/<int:id>',views.editpelatihansaya,name='pelatihan-saya-edit'),
	path('destroy-pelatihan-saya/<int:id>',views.destroypelatihansaya,name='pelatihan-saya-destroy'),
]

pasien/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cari-propinsi/<int:negara_id>', views.propinsi_list, name = 'propinsi_list'),
    path('cari-kota/<int:propinsi_id>', views.kota_list, name = 'kota_list'),
    path('cari-kecamatan/<int:kota_id>', views.kecamatan_list, name = 'kecamatan_list'),
    path('cari-kelurahan/<int:kecamatan_id>', views.kelurahan_list, name = 'kelurahan_list')
]

karyawan/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from .tables import KaryawanTable,BerkasSayaTable,BerkasKaryawanTable,KarirKaryawanTable,RiwayatPendidikanKaryawanTable,PelatihanKaryawanTable,KarirSayaTable,RiwayatPendidikanSayaTable,PelatihanSayaTable,AbsensiKaryawanTable
from .models import Karyawan,BerkasKaryawan,KarirKaryawan,RiwayatPendidikanKaryawan,PelatihanKaryawan,AbsensiKaryawan
from .filters import KaryawanFilter,BerkasSayaFilter,BerkasKaryawanFilter,KarirKaryawanFilter,RiwayatPendidikanKaryawanFilter,PelatihanKaryawanFilter,KarirSayaFilter,RiwayatPendidikanSayaFilter,PelatihanSayaFilter,AbsensiKaryawanFilter
from .forms import KaryawanForm,BerkasSayaForm,BerkasKaryawanForm,KarirKaryawanForm,RiwayatPendidikanKaryawanForm,PelatihanKaryawanForm,KarirSayaForm,RiwayatPendidikanSayaForm,PelatihanSayaForm,DataKaryawanSayaForm
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db.models import ProtectedError
from django_tables2 import RequestConfig
from django.contrib.auth.decorators import login_required,permission_required


#========================================================================================================================
@login_required
def printidcardkaryawan(request,id):
    data_karyawan = get_object_or_404(Karyawan, id = id)
    context = {
        'data':data_karyawan,
    }
    return render(request,'cv_saya/cetak_id_card.html',context)

#========================================================================================================================
@login_required
@permission_required('karyawan.view_absensikaryawan')
def showabsensikaryawan(request,id):
    data =get_object_or_404(AbsensiKaryawan,pk=id) 
    context = {
        'title':'Absensi Karyawan',
        'data':data,
    }
    return render(request,'absensi_karyawan/show.html',context)

#========================================================================================================================
@login_required
@permission_required('karyawan.view_absensikaryawan')
def indexabsensikaryawan(request):
    f = AbsensiKaryawanFilter(request.GET, queryset=AbsensiKaryawan.objects.all().order_by('-pk'))
    table_absensi_karyawan = AbsensiKaryawanTable(f.qs)
    table_absensi_karyawan.paginate(page=request.GET.get("page", 1), per_page=50)
    context = {
        'tabelnya':table_absensi_karyawan,
        'title':'Absensi Karyawan',
        'filter':f,
    }
    return render(request,'absensi_karyawan/index.html',context)

#========================================================================================================================
@login_required
def datakaryawansaya(request):
    user = request.user
    cek_relasi = Karyawan.objects.filter(user=user).count()
    if(cek_relasi<=0):
            messages.error(request, 'User tidak memiliki relasi dengan karyawan')
            return redirect('dashboard')
    else:
        obj = get_object_or_404(Karyawan, user = user)
        if request.method == 'POST':
            form = DataKaryawanSayaForm(request.POST or None,request.FILES, instance = obj)
            if form.is_valid():
                form.save()
                messages.success(request, 'Data Berhasil Diedit')
                return redirect('karyawan:data-karyawan-saya')
        else:
            form = DataKaryawanSayaForm(request.POST or None,instance = obj)
        
        context={
            'form':form,
            'title':'Data Karyawan Saya',
            'status_form':'Edit Data',
        }
    return render(request,'data_karyawan_saya/form.html',context)

#========================================================================================================================
@login_required
def cv_karyawan(request,id):
    data_karyawan = get_object_or_404(Karyawan, id = id)
    data_riwayat_pendidikan = RiwayatPendidikanKaryawan.objects.filter(karyawan=Karyawan.objects.get(id=id))
    data_pelatihan = PelatihanKaryawan.objects.filter(karyawan=Karyawan.objects.get(id=id))
    data_karir = KarirKaryawan.objects.filter(karyawan=Karyawan.objects.get(id=id))
    data_berkas = BerkasKaryawan.objects.filter(karyawan=Karyawan.objects.get(id=id)).filter(status_berkas='Berkas Diterima')
    context = {
        'data':data_karyawan,
        'data_riwayat_pendidikan':data_riwayat_pendidikan,
        'data_pelatihan':data_pelatihan,
        'data_karir':data_karir,
        'data_berkas':data_berkas,
    }
    return render(request,'karyawan/cv.html',context)

#========================================================================================================================
@login_required
@permission_required('karyawan.cv_saya')
def cv_saya(request):
    user = request.user
    cek_relasi = Karyawan.objects.filter(user=user).count()
    if(cek_relasi<=0):
            messages.error(request, 'User tidak memiliki relasi dengan karyawan')
            return redirect('dashboard')
    else:
        data_karyawan = get_object_or_404(Karyawan, user = user)
        data_riwayat_pendidikan = RiwayatPendidikanKaryawan.objects.filter(karyawan=Karyawan.objects.get(user=user))
        data_pelatihan = PelatihanKaryawan.objects.filter(karyawan=Karyawan.objects.get(user=user))
        data_karir = KarirKaryawan.objects.filter(karyawan=Karyawan.objects.get(user=user))
        data_berkas = BerkasKaryawan.objects.filter(karyawan=Karyawan.objects.get(user=user)).filter(status_berkas='Berkas Diterima')
        context = {
            'data':data_karyawan,
            'data_riwayat_pendidikan':data_riwayat_pendidikan,
            'data_pelatihan':data_pelatihan,
            'data_karir':data_karir,
            'data_berkas':data_berkas,
        }
    return render(request,'cv_saya/index.html',context)

#========================================================================================================================
@login_required
@permission_required('karyawan.pelatihan_saya')
def destroypelatihansaya(request,id):
    user = request.user
    cek_relasi = Karyawan.objects.filter(user=user).count()
    if(cek_relasi<=0):
            messages.error(request, 'User tidak memiliki relasi dengan karyawan')
            return redirect('dashboard')
    else:
        if request.method == 'POST':
            data_dihapus = PelatihanKaryawan.objects.get(id=id)
            try:
                data_dihapus.delete()
                messages.success(request, 'Data Berhasil Dihapus')
                return redirect('karyawan:pelatihan-saya-index')
            except ProtectedError:
                messages.error(request, 'Data Gagal Dihapus')
                return redirect('karyawan:pelatihan-saya-destroy',id=id)
        
        data =get_object_or_404(PelatihanKaryawan,pk=id) 
        context = {
            'data':data,
        }
    return render(request,'pelatihan_saya/delete.html',context)

#========================================================================================================================
@login_required
@permission_required('karyawan.pelatihan_saya')
def editpelatihansaya(request,id):
    user = request.user
    cek_relasi = Karyawan.objects.filter(user=user).count()
    if(cek_relasi<=0):
            messages.error(request, 'User tidak memiliki relasi dengan karyawan')
            return redirect('dashboard')
    else:
        obj = get_object_or_404(PelatihanKaryawan, id = id)
        form = PelatihanSayaForm(request.user,request.POST or None, instance = obj)
        if form.is_valid():
            form.save()
            messages.success(request, 'Data Berhasil Diedit')
            return redirect('karyawan:pelatihan-karyawan-index')
        
        context={
            'form':form,
            'title':'Pelatihan Saya',
            'status_form':'Edit Data',
        }
    return render(request,'pelatihan_saya/form.html',context)

#========================================================================================================================
@login_required
@permission_required('karyawan.pelatihan_saya')
def showpelatihansaya(request,id):
    data =get_object_or_404(PelatihanKaryawan,pk=id) 
    context = {
        'title':'Pelatihan Saya',
        'data':data,
    }
    return render(request,'pelatihan_saya/show.html',context)


#========================================================================================================================
@login_required
@permission_required('karyawan.pelatihan_saya')
def createpelatihansaya(request):
    user = request.user
    cek_relasi = Karyawan.objects.filter(user=user).count()
    if(cek_relasi<=0):
            messages.error(request, 'User tidak memiliki relasi dengan karyawan')
            return redirect('dashboard')
    else:
        form = PelatihanSayaForm(request.user,request.POST or None)
        if form.is_valid():
            obj = form.save(commit=False) # Return an object without saving to the DB
            obj.karyawan = Karyawan.objects.get(user=user) # Add an author field which will contain current user's id
            obj.save()

            messages.success(request, 'Data Berhasil Disimpan')
            return redirect('karyawan:pelatihan-saya-index')
        
        context={
            'form':form,
            'title':'Pelatihan Karyawan',
            'status_form':'Edit Data',
        }
    return render(request,'pelatihan_saya/form.html',context)

#========================================================================================================================
@login_required
@permission_required('karyawan.pelatihan_saya')
def indexpelatihansaya(request):
    user = request.user
    cek_relasi = Karyawan.objects.filter(user=user).count()
    if(cek_relasi<=0):
            messages.error(request, 'User tidak memiliki relasi dengan karyawan')
            return redirect('dashboard')
    else:

karyawan/templates/berkas_saya/delete.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="jumbotron mt-3">
                        <h1 class="display-4">Hapus Data ?</h1>
                        <p class="lead">
                            Hapus data Berkas <b>{{data.berkas.name|cut:'documents/'}}</b>
                        </p>
                        <hr class="my-4">
                        <p>Data tidak dapat dipulihkan kembali setelah di hapus</p>
                        <p class="lead">
                            
                        <form action="" method="post">
                            {% csrf_token %}
                            <button type="button" onclick="history.go(-1)" class="btn btn-danger"
                                role="button">Back</button>
                                <button class="btn btn-success" type="submit">Delete</button>
                        </form>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

karyawan/templates/berkas_saya/form.html
{% extends 'layout/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1 class="m-0">{{title}}</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{{status_form}}</h3>
                            <div class="card-tools">
                                <button type="button" onclick="history.go(-1)"class="btn btn-sm btn-danger">Back</button>
                            </div>
                        </div>
                        <div class="card-body">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form form bound_css_class='' %}
                                <button type="submit" class="btn btn-success">Save Data</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

karyawan/templates/berkas_saya/index.html
{% extends 'layout/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load render_table from django_tables2 %}
{% block content %}
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1 class="m-0">{{title}}</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Filter Data</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                        class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body pt-1 pb-1">
                            <form method="get" class="mb-3 form row">
                                {% for field in filter.form  %}
                                <div class="col-md-3">
                                    {% bootstrap_field field bound_css_class='m-1' %}
                                </div>
                                {% endfor %}
                                <div class="form-group m-1 col-md-12">
                                    <button class="btn btn-secondary btn-sm" type="submit">Cari Data</button>
                                </div>
                            </form>
                        </div>
                        
                    </div>
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">List Data</h3>
                            <div class="card-tools">
                                <a href="{% url 'karyawan:berkas-saya-create' %}">
                                    <button type="button" class="btn btn-default btn-sm">
                                        Add Data
                                    </button>
                                </a>
                            </div>
                        </div>
                        <div class="card-body">
                            {% if messages %}
                            {% for message in messages %}
                            {% if message.tags == "error" %}
                            <div class="alert alert-danger alert-dismissible"><button type="button" class="close"
                                    data-dismiss="alert" aria-hidden="true">×</button><i
                                    class="fa fa-lg fa-check-circle-o"></i> {{ message }}</div>
                            {% else %}
                            <div class="alert alert-success alert-dismissible"><button type="button" class="close"
                                    data-dismiss="alert" aria-hidden="true">×</button><i
                                    class="fa fa-lg fa-check-circle-o"></i> {{ message }}</div>
                            {% endif %}
                            {% endfor %}
                            {% endif %}
                            <div class="table-responsive">
                                {% render_table tabelnya %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

karyawan/templates/berkas_saya/show.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1 class="m-0">{{title}}</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="m-0">Detai Data</h5>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'karyawan:berkas-saya-index' %}" class="btn btn-sm btn-danger">Back</a>
                            <a href="{% url 'karyawan:berkas-saya-destroy' data.id %}" class="btn btn-sm btn-warning">Delete</a>
                            <a href="{% url 'karyawan:berkas-saya-edit' data.id %}" class="btn btn-sm btn-success">Edit</a>
                            <table class="table table-bordered mt-3">
                                <tbody>
                                    <tr>
                                        <td width="20%">Id</td>
                                        <td>{{data.id}}</td>
                                    </tr>
                                    <tr>
                                        <td width="20%">Karyawan</td>
                                        <td>{{data.karyawan}}</td>
                                    </tr>
                                    <tr>
                                        <td width="20%">Nama Berkas</td>
                                        <td>{{data.nama_berkas}}</td>
                                    </tr>
                                    <tr>
                                        <td width="20%">Kategori</td>
                                        <td>{{data.kategori}}</td>
                                    </tr>
                                    <tr>
                                        <td width="20%">Status Berkas</td>
                                        <td>{{data.status_berkas}}</td>
                                    </tr>
                                    <tr>
                                        <td width="20%">Berkas</td>
                                        <td>
                                            <a href="{% get_media_prefix %}{{data.berkas}}" target="blank">{{data.berkas.name|cut:'documents/'}}</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td width="20%">Verifikator</td>
                                        <td>{{data.verifikator}}</td>
                                    </tr>
                                    <tr>
                                        <td width="20%">Keterangan Verifikator</td>
                                        <td>{{data.keterangan_verifikator}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}